### ISSUE TITLE
Can't store notes on first launch

### ISSUE THREAD

**Issue by IpswichMapper** [hauke96/GeoNotes#15]
After tapping on the map to create a note, clicking on move, delete, ok does nothing. It doesn't even create the button pressing animation

Device is pocophone f1 running lineage os

**Comment by IpswichMapper** [comment]
Sometimes, however, after pressing the delete button 10 times, it does work. But that is rare.

Is this happening to you? If not, what devices did you test the application on?

**Comment by hauke96** [comment]
Hi, thanks for reporting this issue.

I never experiences anything like that. I also use a phone with LineageOS (16.0) and also use emulated phones. What LineageOS do you have? Have you changed anything on your phone (resolution, scaling, font sizes, etc. etc.)?

**Comment by IpswichMapper** [comment]
Hello, it turns out that this is only an issue on the very first launch of the application. Even though I grant storage permissions, it seems that the app cannot save these notes (hence the OK, MOVE and DELETE buttons don't work). 

However, closing the app, removing it from the recents drawer and then re-opening it works. (This does delete the notes you created on the first launch).

**Comment by hauke96** [comment]
Thanks for figuring that out, is reassures me that the app works after a relaunch. Of course I'll work on that.

**Comment by hauke96** [comment]
Figured it out:
Root of this problem was a faulty implementation of the permission request. The app asked over and over again for the storage and location permission (even if it was already granted). This caused the app to become stuck in this infinite loop and therefore the whole UI stopped working more or less.

I fixed it in version v1.0.3 and already created a release for this. It may take a while until it's available in F-Droid but you can manually download the APK if you want. But as you figured out, restarting the app is a good workaround :wink:
