### ISSUE TITLE
Zoom buttons zooming twice

### ISSUE THREAD

**Issue by siiky** [hauke96/GeoNotes#47]
Sorry if there's already an issue about this but I couldn't find any.

When using the buttons to zoom in or out, it zooms twice -- once when you press it and again when you release it. I suppose this isn't the intended behaviour.

The workaround I've found is to press the button but move the finger out of it before releasing.

**Comment by hauke96** [comment]
Hi, thanks for the issue. This happens when tapping slowly on the zoom buttons and is unfortunately an behavior of the underlying OsmDroid framework I use. I don't have direct control over the buttons and their behavior without re-implementing everything.

I created an [issue at the OsmDroid repository](https://github.com/osmdroid/osmdroid/issues/1733), maybe there will be a fix on that but maybe they don't consider this as a bug. We will see.

**Comment by SiIky** [comment]
I see, thanks for the reply (and the details in the other issue)!

**Comment by hauke96** [comment]
Just updated the used OsmDroid version, which fixes this bug. This fix will be available in the next GeoNotes release.
