### ISSUE TITLE
add a button with a list of points to the top status bar

### ISSUE THREAD

**Issue by OmlineEditor** [hauke96/GeoNotes#58]
now in the status bar there is only the my position and export button. I also ask you to add a button with the entire list of points, so it's faster to open the list.

**Comment by hauke96** [comment]
What version of GeoNotes do you use? Because since [1.4.0](https://github.com/hauke96/GeoNotes/releases/tag/v1.4.0) there's a button which shows a list of all notes.

**Comment by OmlineEditor** [comment]
My version 1.4.3 
![list](https://user-images.githubusercontent.com/13348933/151630170-8cd7aa02-63a2-4c55-af4f-cd029dac027c.jpg)

**Comment by hauke96** [comment]
Ah, I see.

Unfortunately that's the default behavior of that android icon toolbar. It's a design decision Google made to not use the whole available space (probably to not make the toolbar to crowded with lots of icons). But I'm not completely innocent as I'm not using this toolbar as intended, but I don't really like the alternatives Googles material design and Android SDK provide.

I could enforce it, so that all buttons (or the first few) are visible, but that might not work well on smaller devices or devices with higher UI zoom or higher font sizes.

So unfortunately we have to live with this behavior.

**Comment by OmlineEditor** [comment]
I think you can configure it so that if the screen allows you to accommodate all the buttons, then all these buttons are shown, if the screen is small, then let there be a menu with drop-down lists.

**Comment by hauke96** [comment]
That's unfortunately not how the Android action bar works, it just allows certain settings for the behavior of the icons: Never show them, always show them or show them if there's space available (which I currently use). Those are all options that exist and you cannot manually change their behavior.

**Comment by OmlineEditor** [comment]
you are wrong, you can completely control how many buttons you have on the panel, in other applications I have more buttons and everything fits. look at the detailed settings, maybe you forgot to add something.

**Comment by hauke96** [comment]
As I said: I can always show all buttons, but then smaller screens or screens with a higher UI scale factor won't be able to show all buttons as there's not enough space. If you have a concrete code example, API documentation or other resource, feel free to share it with me.
