### ISSUE TITLE
formatting for the exported in gpx file

### ISSUE THREAD

**Issue by OmlineEditor** [hauke96/GeoNotes#63]
you have 2 options for exporting to a geojson and gpx file. the geojson file is very well structured and I have beautiful formatting and line splitting and has indents. it is easy and convenient to read. the gpx file is written in one line without splitting into lines and has no indentation. it's very hard to read and edit. I ask you to export to a file using formatting and splitting into lines.

**Comment by hauke96** [comment]
Hi, yes that's in deed a bummer. Unfortunately the GPX library I use does not support this but other users already reported an [issue](https://github.com/himanshu-soni/gpx-parser/issues/28) at the library's github repo. Maybe the library will support this some day. I know that there are other GPX libraries out there and I tried a few but the one I'm using now was the most comfortable to use and I'm not switching just because of missing formatting. If I find the time I might add some very basic manual formatting, but we'll see.

Generally those exports are not meant to be read or edited by humans anyway. I also always recommend a special editing program for the exports like Viking, GpsMaster or gpx.studio. It's probably more comfortable and less error-prone :wink:

**Comment by hauke96** [comment]
Added formatting of the GPX output, this will be part of the next release (version 1.4.4).
